spring:
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  datasource:
    url: jdbc:h2:mem:${H2_DB_NAME}
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
yandex:
  api:
    token: ${YANDEX_API_TOKEN}
  folder:
    id: ${YANDEX_FOLDER_ID}
server:
  port: 8081